"use client";

import { useState } from "react";

export function CreateProjectForm() {
  const [state, setState] = useState<{ error?: string; success?: string }>({});
  async function submit(formData: FormData) {
    setState({});
    const response = await fetch("/api/projects", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: formData.get("title"), description: formData.get("description"), category: formData.get("category"), requiredSkills: String(formData.get("skills")).split(",").map((skill) => skill.trim()).filter(Boolean), requiredRoles: String(formData.get("roles")).split(",").map((role) => role.trim()).filter(Boolean), maxTeamSize: formData.get("maxTeamSize") }) });
    const data = await response.json();
    setState(response.ok ? { success: `Project created. Its URL slug is ${data.project.slug}.` } : { error: data.error ?? "Could not create project." });
  }
  return <form action={submit} className="mt-8 grid gap-5 rounded-2xl border border-white/12 bg-white/[0.07] p-6 shadow-xl shadow-indigo-950/15 backdrop-blur"><label className="grid gap-2 text-sm font-medium text-indigo-100">Project title<input required name="title" maxLength={100} className="rounded-lg border border-white/15 bg-[#100a3d] px-3 py-2.5 text-white outline-none focus:border-indigo-200" placeholder="e.g. Campus Carbon" /></label><label className="grid gap-2 text-sm font-medium text-indigo-100">One-paragraph pitch<textarea required name="description" maxLength={2000} rows={5} className="rounded-lg border border-white/15 bg-[#100a3d] px-3 py-2.5 text-white outline-none focus:border-indigo-200" placeholder="What are you building and why does it matter?" /></label><div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 text-sm font-medium text-indigo-100">Category<input required name="category" className="rounded-lg border border-white/15 bg-[#100a3d] px-3 py-2.5 text-white outline-none focus:border-indigo-200" placeholder="Hackathon, open source…" /></label><label className="grid gap-2 text-sm font-medium text-indigo-100">Maximum team size<input required name="maxTeamSize" type="number" min="2" max="20" defaultValue="4" className="rounded-lg border border-white/15 bg-[#100a3d] px-3 py-2.5 text-white outline-none focus:border-indigo-200" /></label></div><label className="grid gap-2 text-sm font-medium text-indigo-100">Required skills <span className="font-normal text-indigo-100/45">Comma separated</span><input required name="skills" className="rounded-lg border border-white/15 bg-[#100a3d] px-3 py-2.5 text-white outline-none focus:border-indigo-200" placeholder="TypeScript, MongoDB, UI/UX" /></label><label className="grid gap-2 text-sm font-medium text-indigo-100">Required roles <span className="font-normal text-indigo-100/45">Comma separated</span><input required name="roles" className="rounded-lg border border-white/15 bg-[#100a3d] px-3 py-2.5 text-white outline-none focus:border-indigo-200" placeholder="Frontend engineer, Designer" /></label>{state.error && <p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-200">{state.error}</p>}{state.success && <p className="rounded-lg bg-white/10 p-3 text-sm text-indigo-100">{state.success}</p>}<button className="w-fit rounded-lg border border-white/30 bg-white/10 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-white hover:text-indigo-950">Publish project</button></form>;
}
