import Link from "next/link";
import { featuredProjects } from "@/features/projects/data";
import { ProjectCard } from "@/features/projects/components/project-card";
import { requireUser } from "@/server/require-user";

export default async function DashboardPage() {
  const user = await requireUser();
  const firstName = user.name?.split(" ")[0] ?? "there";
  return <div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-teal-300">Your workspace</p><h1 className="mt-2 text-3xl font-semibold text-white">Good to see you, {firstName}.</h1><p className="mt-2 max-w-xl text-slate-400">Complete your profile, find a project with a clear need, and move the conversation into a shared hub.</p></div><Link href="/projects/new" className="rounded-lg bg-teal-400 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-teal-300">Create project</Link></div><section className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><p className="text-sm text-slate-400">Profile strength</p><p className="mt-2 text-3xl font-semibold text-white">Start here</p><Link href={`/profile/${user.name?.toLowerCase().replaceAll(" ", "-") ?? "me"}`} className="mt-4 inline-block text-sm font-semibold text-teal-300">Finish profile →</Link></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><p className="text-sm text-slate-400">Open invitations</p><p className="mt-2 text-3xl font-semibold text-white">0</p><Link href="/invitations" className="mt-4 inline-block text-sm font-semibold text-teal-300">Review invitations →</Link></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><p className="text-sm text-slate-400">Best next move</p><p className="mt-2 text-xl font-semibold text-white">Find a project</p><Link href="/projects" className="mt-4 inline-block text-sm font-semibold text-teal-300">Explore projects →</Link></div></section><section className="mt-12"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold text-white">Recruiting now</h2><Link href="/projects" className="text-sm font-semibold text-teal-300">All projects →</Link></div><div className="grid gap-5 lg:grid-cols-3">{featuredProjects.map((project) => <ProjectCard key={project.id} project={project} />)}</div></section></div>;
}
