import Link from "next/link";
import { featuredProjects } from "@/features/projects/data";
import { ProjectCard } from "@/features/projects/components/project-card";
import { requireUser } from "@/server/require-user";
import { findProfileById } from "@/server/repositories/users";
import { GitHubSyncButton } from "@/features/profiles/components/github-sync-button";
import { AvailabilityControl } from "@/features/profiles/components/availability-control";
import { DashboardCopilotLayout } from "@/features/ai/components/dashboard-copilot-layout";

export default async function DashboardPage() {
  const user = await requireUser();
  const profile = await findProfileById(user.id);
  const firstName = user.name?.split(" ")[0] ?? "there";
  const profileUsername = profile?.username ?? user.name?.toLowerCase().replaceAll(" ", "-") ?? "me";
  return <DashboardCopilotLayout><div className="mx-auto max-w-6xl"><div className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-gradient-to-br from-indigo-950/85 via-violet-950/80 to-fuchsia-900/60 p-6 shadow-2xl shadow-indigo-950/40 md:p-9"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-fuchsia-400/25 blur-3xl" /><div className="relative flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium text-violet-200">Your workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-white">Good to see you, {firstName}.</h1><p className="mt-2 max-w-xl text-indigo-100/70">Complete your profile, find a project with a clear need, and move the conversation into a shared hub.</p></div><Link href="/projects/new" className="rounded-lg border border-white/30 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-white hover:text-indigo-950">Create project</Link></div></div><section className="dashboard-summary-grid mt-8 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/15 bg-white/10 p-5 shadow-xl shadow-indigo-950/10 backdrop-blur"><p className="text-sm text-indigo-100/65">Profile strength</p><p className="mt-2 text-3xl font-semibold text-white">Start here</p><Link href={`/profile/${profileUsername}`} className="mt-4 inline-block text-sm font-semibold text-indigo-100 hover:text-white">Finish profile →</Link><AvailabilityControl initialAvailability={profile?.availability ?? "available"} /></div><div className="rounded-2xl border border-white/15 bg-white/10 p-5 shadow-xl shadow-indigo-950/10 backdrop-blur"><p className="text-sm text-indigo-100/65">GitHub profile</p><p className="mt-2 text-xl font-semibold text-white">Keep it current</p><div className="mt-4"><GitHubSyncButton /></div></div><div className="rounded-2xl border border-white/15 bg-white/10 p-5 shadow-xl shadow-indigo-950/10 backdrop-blur"><p className="text-sm text-indigo-100/65">Best next move</p><p className="mt-2 text-xl font-semibold text-white">Find a project</p><Link href="/projects" className="mt-4 inline-block text-sm font-semibold text-indigo-100 hover:text-white">Explore projects →</Link></div></section><section className="mt-12"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold text-white">Recruiting now</h2><Link href="/projects" className="text-sm font-semibold text-indigo-100 hover:text-white">All projects →</Link></div><div className="dashboard-project-grid grid gap-5 lg:grid-cols-3">{featuredProjects.map((project) => <ProjectCard key={project.id} project={project} />)}</div></section></div></DashboardCopilotLayout>;
}
