import Link from "next/link";
import { SiteHeader } from "@/components/layout/site-header";
import { TechPill } from "@/components/shared/tech-pill";
import { ProjectCard } from "@/features/projects/components/project-card";
import { featuredProjects } from "@/features/projects/data";

export default function Home() {
  return <><SiteHeader /><main>
    <section className="relative overflow-hidden px-5 pb-20 pt-20 md:px-10 md:pb-28 md:pt-28"><div className="absolute inset-x-0 top-0 -z-10 h-[460px] bg-[radial-gradient(ellipse_at_top,_rgba(20,184,166,0.18),transparent_60%)]" />
      <div className="mx-auto max-w-5xl text-center"><p className="mb-5 text-sm font-semibold uppercase tracking-[0.2em] text-teal-300">Build with people who ship</p><h1 className="mx-auto max-w-4xl text-5xl font-semibold tracking-tight text-white md:text-7xl">The right teammate changes the whole project.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">Project Matchmaker connects developers through verified GitHub work, shared technical goals, and private spaces to build together.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/sign-in" className="rounded-lg bg-teal-400 px-5 py-3 font-semibold text-slate-950 hover:bg-teal-300">Find your next team</Link><Link href="/projects" className="rounded-lg border border-slate-700 px-5 py-3 font-semibold text-slate-200 hover:border-slate-500">Browse projects</Link></div></div>
    </section>
    <section className="mx-auto grid max-w-6xl gap-4 px-5 pb-20 md:grid-cols-3 md:px-10"><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><p className="text-3xl font-semibold text-white">GitHub-backed</p><p className="mt-2 text-sm leading-6 text-slate-400">Profiles show real repositories, skills, and work—not empty claims.</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><p className="text-3xl font-semibold text-white">Purposeful matching</p><p className="mt-2 text-sm leading-6 text-slate-400">Match a project’s exact needs with developers ready to contribute.</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6"><p className="text-3xl font-semibold text-white">One private hub</p><p className="mt-2 text-sm leading-6 text-slate-400">Move from invitation to a focused chat and team workspace.</p></div></section>
    <section className="border-t border-slate-800 bg-[#091728] px-5 py-20 md:px-10"><div className="mx-auto max-w-6xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-teal-300">Actively recruiting</p><h2 className="mt-2 text-3xl font-semibold text-white">Projects worth joining</h2></div><Link href="/projects" className="text-sm font-semibold text-teal-300 hover:text-teal-100">See all projects →</Link></div><div className="grid gap-5 md:grid-cols-3">{featuredProjects.map((project) => <ProjectCard key={project.id} project={project} />)}</div></div></section>
    <section className="mx-auto max-w-4xl px-5 py-20 text-center md:px-10"><p className="text-sm font-semibold text-teal-300">Made for builders</p><h2 className="mt-3 text-3xl font-semibold text-white">Bring the skills. Find the momentum.</h2><div className="mt-6 flex flex-wrap justify-center gap-2">{["TypeScript", "Python", "UI/UX", "Data", "DevOps", "Mobile"].map((skill) => <TechPill key={skill} label={skill} subtle />)}</div></section>
  </main></>;
}
